name: kgz_news
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.2
  firebase_core_desktop: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  image_picker: ^0.8.6
  flutter_form_builder: ^4.0.0-pre.6
  
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  flutter_lints: ^2.0.0

flutter: 
  
  uses-material-design: true
  
  assets:
    - assets/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  