// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOFrjHxXEEnt6aJ-yyohm0ZZq29jENu6U',
    appId: '1:39410882610:web:78aa5208eeea80ae13442b',
    messagingSenderId: '39410882610',
    projectId: 'newsapp-5b4bd',
    authDomain: 'newsapp-5b4bd.firebaseapp.com',
    databaseURL: 'https://newsapp-5b4bd-default-rtdb.firebaseio.com',
    storageBucket: 'newsapp-5b4bd.appspot.com',
    measurementId: 'G-RKNZWB43B1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOLrnZQmGtYRP1mzOnB_M-wEXIO7tX0FM',
    appId: '1:39410882610:android:c0bad7e6b36d4e2713442b',
    messagingSenderId: '39410882610',
    projectId: 'newsapp-5b4bd',
    databaseURL: 'https://newsapp-5b4bd-default-rtdb.firebaseio.com',
    storageBucket: 'newsapp-5b4bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4AKeEZFv0X9WLrUgA46-iA89u0vJsOwI',
    appId: '1:39410882610:ios:c454dba87d73b83113442b',
    messagingSenderId: '39410882610',
    projectId: 'newsapp-5b4bd',
    databaseURL: 'https://newsapp-5b4bd-default-rtdb.firebaseio.com',
    storageBucket: 'newsapp-5b4bd.appspot.com',
    iosClientId: '39410882610-rq5m3e62lldo68ns69kc247061s12bbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4AKeEZFv0X9WLrUgA46-iA89u0vJsOwI',
    appId: '1:39410882610:ios:c454dba87d73b83113442b',
    messagingSenderId: '39410882610',
    projectId: 'newsapp-5b4bd',
    databaseURL: 'https://newsapp-5b4bd-default-rtdb.firebaseio.com',
    storageBucket: 'newsapp-5b4bd.appspot.com',
    iosClientId: '39410882610-rq5m3e62lldo68ns69kc247061s12bbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOFrjHxXEEnt6aJ-yyohm0ZZq29jENu6U',
    appId: '1:39410882610:web:fd43f901e3553b3b13442b',
    messagingSenderId: '39410882610',
    projectId: 'newsapp-5b4bd',
    authDomain: 'newsapp-5b4bd.firebaseapp.com',
    databaseURL: 'https://newsapp-5b4bd-default-rtdb.firebaseio.com',
    storageBucket: 'newsapp-5b4bd.appspot.com',
    measurementId: 'G-WYK2P0LRYB',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAOFrjHxXEEnt6aJ-yyohm0ZZq29jENu6U',
    appId: '1:39410882610:web:5fbaf68196521f4113442b',
    messagingSenderId: '39410882610',
    projectId: 'newsapp-5b4bd',
    authDomain: 'newsapp-5b4bd.firebaseapp.com',
    databaseURL: 'https://newsapp-5b4bd-default-rtdb.firebaseio.com',
    storageBucket: 'newsapp-5b4bd.appspot.com',
    measurementId: 'G-TYPJ1JVFBW',
  );
}
